name: AdminMenuUI
main: AdminMenuUI\Main
api: [3.0.0, 4.0.0]
version: 1.0.0
author: anirudh246
commands:
 adminmenu:
    default: op
    aliases: ["am"]
permissons:
  adminmenu.use:
    default: false
